### PR TITLE
Print to standard output only when in 'debug' mode

### PR DESCRIPTION
**Pull request by gasparka**
I am using the REPL UART (since ESP8266 has only one) for communication with my embedded device, thus any print to standard output breaks everything.

### CODE REVIEW

**Comment by gasparka** [comment]
@pfalcon Any reasons for not merging this?

**Comment by pfalcon** [comment]
Things like `print('%.3f %s %s "%s %s"'` are more or less standard web server logging, I'm not sure that should be done only in debug mode.

So, I agree that something needs to be done about that, not sure exactly how and when. To avoid breaking things for people multiple times, I'd prefer to work on "finishing" other core functionality, while keep pondering about this issue.

In the meantime, definitely feel free to use this patch in your projects.

**Comment by gasparka** [comment]
Was hoping to install the dependencies of my project with pip, but i understand your reasons.
Thanks for the clarification :)

**Comment by pfalcon** [comment]
@gasparka: You're right that this issue needs resolving, so I gave a thought how to resolve it in a more general manner (hopefully once and for all), and what came out of it is https://github.com/pfalcon/picoweb/commit/a13e5111a5f62cbbaf229ef08cf0a659740aab01 and https://github.com/pfalcon/picoweb/commit/1fd3eec694e68c80f973e51db924211f0a92a200 . I hope this covers your usecase. If you find any issues, feel free to comment. Otherwise, I'm closing this ticket, thanks for driving it.

**Pull request closed without merging**
