### PR TITLE
Add more simple filetypes

### PR DESCRIPTION
**Pull request by belyalov**
### Filetypes
* Add `.js` - it doesn't work without proper content type
* Change `.png` and `.jpg` to from *image* to proper MIME types.

### Style
Modern editors / IDE have pep8 style check embedded (like Sublime + Anaconda) - so just to make them happy

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks, but this looks like a random collection of random things. If you have any specific issues, I'd recommend to start with opening tickets for them, following the golden rule: one ticket per one issue.

**Comment by belyalov** [comment]
I'd agree that styling could be "random" thing.
However, `.js` file type is real issue.
Browser will not interpret `.js` files as JavaScript unless you provide proper content type.

Do you want me to split this fix (filetypes) from style, open issue and than fix it?

**Comment by pfalcon** [comment]
As suggested above, a ticket should be opened for each separate issue you experience, with enough information provided to assess it. Then discussion will ensue, during which it'll become clear whether there's an issue, or not, whether it's worth being fixed, or not, and if yes, then in which way. For example, on the matter of .js mimetime, you'll be asked to consider how applications like https://github.com/pfalcon/notes-pico and https://github.com/pfalcon/pydashie-picoweb work for other people (e.g. me), contrary to your claims:

> Browser will not interpret .js files as JavaScript

**Comment by belyalov** [comment]
I got your point.
Thanks, closing this one.

**Pull request closed without merging**
