### PR TITLE
Add charset parameter to response.

### PR DESCRIPTION
**Pull request by pwoo**
And default the value to UTF-8.

### CODE REVIEW

**Comment by pwoo** [comment]
RFC4627 requires that JSON is encoded in Unicode, thus it would be good to set the charset parameter of the response to UTF-8 rather than default to ISO-8859-1.

**Comment by pfalcon** [comment]
Can you please specify how to reproduce an issue that this patch fixes?

And I would doubt it fixes it correctly, it adds charset unconditionally to every content-type, how would that work with e.g. binary content-types?

**Comment by pwoo** [comment]
My memory is a bit fuzzy regarding this, but charset will default to ISO-8859-1 when it is not explicitly set; JSON requires Unicode. As a result, some characters were not being displayed correctly.

AFAIK, binary content uses [MIME types](http://www.rfc-editor.org/rfc/rfc2046.txt), e.g. application/octet-stream.

**Comment by pfalcon** [comment]
> AFAIK, binary content uses MIME types, e.g. application/octet-stream.

Exactly, so after you patch, someone doing

~~~
app.start_response(writer, content_type="application/octet-stream")
~~~

will get `application/octet-stream; charset=utf-8`, which is hardly the right Content-Type.

Whereas the behavior you want can be easily achieved with
~~~
app.start_response(writer, content_type="application/json; charset=utf-8")
~~~

 -- without any patching.

> As a result, some characters were not being displayed correctly.

So, if you'd have *exact* steps to reproduce, feel free to share. No hurry and no worry otherwise, I'll keep this on my radar, just will take more time.

**Comment by pwoo** [comment]
Thanks.

You're right and I should have gone though picoweb's logic more thoroughly before pushing the changes.

I don't consider these changes critical at all, but please keep some of these nitpicky RFC header requirements in mind if development is continued in the future.

**Comment by pfalcon** [comment]
If you don't mind, I'd like to keep this open as a reminder.

**Comment by pfalcon** [comment]
Thanks again for bringing this into attention. This issue is now addressed, in a different way, by https://github.com/pfalcon/picoweb/commit/fb4354dc601e81ebc37c4c08b5df342f0833d305 . Specifically, the default Content-Encoding is set to "text/html; charset=utf-8" (instead of older "text/html").

The codebase contains a testcase to reproduce an issue the above change fixes: without the change mentioned, https://github.com/pfalcon/picoweb/blob/master/examples/example_unicode.py will render incorrectly in real-world browsers like Firefox (specifically, it'll assume that text encoding is ISO-8859-1 aka "Western").

**Comment by pfalcon** [comment]
Let's consider specifically this matter:

> RFC4627 requires that JSON is encoded in Unicode, thus it would be good to set the charset parameter of the response to UTF-8 rather than default to ISO-8859-1.

RFC4627 was obsoleted by RFC7159 https://tools.ietf.org/html/rfc7159 , so I'll use that as the reference:

> The default
   encoding is UTF-8

We'll assume that the word "default" means "default", i.e. if encoding is not specified, it should be assumed to be UTF-8.

> Note:  No "charset" parameter is defined for this registration.
      Adding one really has no effect on compliant recipients.

These can be interpreted in 2 ways:

1. RFC7159 doesn't define "charset: a_charset_specifically_for_rfc7159".
2. RFC7159 doesn't stipulate the need to use "charset: " specification.

We'll assume both.

Thus, nothing in picoweb's JSON related functionality is in conflict with RFC7159. I'll thus close this issue.

Reports of real-world issue cases are welcome though. For example, if a well-known web technology implementation like Firefox or Chrome has issues with recognized JSON, or its encoding, as generated by picoweb, please provides steps to reproduce this.

(There was issue with recognizing encoding of HTML output generated by picoweb, and it's was fixed, per above.)

**Pull request closed without merging**
