### PR TITLE
Add extra_headers argument to sendfile and start_response

### PR DESCRIPTION
**Pull request by orzechow**
This minimal implementation allows to set additional response headers like `Content-Encoding` or `Cache-Control`.

Working example providing already gzipped stylesheets instead of raw content if available:

```python
@app.route(re.compile('^\/(.+\.css)$'), methods=['GET'])
def styles(request, response):
    file_path = request.url_match.group(1)

    if b"gzip" in request.headers[b"Accept-Encoding"]:
        print("client accepts gzip")
        file_path_gzip = file_path + ".gz"
        import os
        if file_path_gzip in os.listdir("webapp"):
            print("sending " + file_path_gzip)
            yield from app.sendfile(response, file_path_gzip, b"text/css", b"Content-Encoding: gzip")
            return

    yield from app.sendfile(response, file_path, b"text/css")
```

### CODE REVIEW

**Comment by orzechow** [comment]
This would close #25 and #26

**Comment by pfalcon** [comment]
Looks good for the first try. Discussion:

1. It's ok that you left out passing headers as a dict out of this patch, can be added later.

2. There're now a bit many params, I don't know if people will want to pass headers by keyword arguments. Then "extra_headers" is a bit long, how about naming it "headers"?

3. It seems that you're calling headers to be passed in more or less adhoc format, like b"Foo: bar\r\nFoo2: baz", i.e. no EOL at the end of passed string. Is that grounded? More natural would be call (and expect) that user passes complete header lines: b"Foo: bar\r\nFoo2: baz\r\n". (Number of function calls should still be optimized on the fast path, i.e. it's ok to add a bit of duplication.)

(Please don't haste with any changes, let's discuss the points above first, like, of you have strong counter-arguments, then maybe above shouldn't be done.)

**Comment by orzechow** [comment]
1. As you've worried about additional file size, I left out the dict support. If extra headers are a rarely used feature, additional bytes for dict support might not be worth it. It's up to you ;)
2. "headers" alone are a little bit misleading, as it's not the full, but extra, headers. I'm always for descriptive names (especially if there is no doc string explaining arguments). But I'm flexible, I'll add an example with headers anyways.
3. Well, "\r\n" is a line break, so yes it would be more logical to see it after each extra header line, but it's not necessarily more natural to have a line break at the end of the string (depending on the user).  
So my implementation supports both, instead of breaking calls without ending line breaks.

**Comment by pfalcon** [comment]
Happy New Year!

2: Well, there're only so much of meaning you can pack into a couple of words anyway, and hopefully from the other params, it should be clear that it's indeed extra/additional args. Terseness wins here IMHO.

There should be some docs of course (eventually). I avoid docstrings, currently uPy skips them, but what if later some version will store them?

3:
> So my implementation supports both, instead of breaking calls without ending line breaks.

Well, not really. If user supplies a string with "\r\n" at the end, your implementation will send out "\r\n" as content. So, I suggest we go for an easy to explain way where "headers" arg is concatenation of b"Foo: bar\r\n" substrings.

So, please make those changes and squash it into one commit, and it's ready to go!

**Comment by orzechow** [comment]
Happy New Year as well!

3. You're right the response is empty. I missed that when testing, because the transmission and error code have been flawless :man_facepalming:

**Comment by orzechow** [comment]
Have a look at the squashed commit. I've added an example, too.

**Comment by pfalcon** [comment]
Thanks. There was still a couple of problems: while changes to start_response() should have been squashed (as they changes the same thing twice), an example should have gone as a separate commit. The criteria whether something should be a separate commit is "whether it can be reverted separately from anything else?"

Another issue is that commit messages should follow existing format used in the repository - "git log" will make it clear, and this rule of thumb works for any project, highly recommended.

So, I've cleaned that up, and merged just changes to `picoweb/__init__.py` as https://github.com/pfalcon/picoweb/commit/b3c00031acd8f3873f4c0accd872718ef8712b43

In https://github.com/pfalcon/picoweb/commit/3f332ada71e3d3a1f6c3bd37d5ad42f5f4e629aa, I reintroduce fast path I was talking about above.

**Comment by pfalcon** [comment]
Now let's look at the example (you'll need to rebase your branch on the latest master of course).

My understanding that the example should show serving a gzipped resource, but I don't see it being included in the patch. Also, picoweb's convention is to store static files in `static/` subdir, would be nice to promote it in the examples.

Also, I guess, the code can be simplified - just decide what filename and headers to serve and call sendfile() once.

Also minor things like no EOL at the end of line (github shows such cases clearly).

Thanks again!

**Comment by pfalcon** [comment]
In https://github.com/pfalcon/picoweb/commit/dd68a0d6fa99d18548b60c1801cf283e8a28bf87, I implemented passing extra headers by dict. I indeed would like to keep the codebase minimal, but also would like to provide generic enough functionality, and close the topic of specifying extra headers in responses. So, now people have a choice: for static headers, it's more efficient to pass them fully constructed as bytes, but if header values need to be dynamic, using dict would be more efficient than formatting all needed headers as a string on user side.

**Comment by orzechow** [comment]
Hey, my job got me again ;)  
But here we go. I've rebased to the current master, created a separate example commit, matching your commit message style, minimized the example as you suggested and moved the stylesheet to a "static" dir (within the examples dir).

The only thing I didn't do: Including the gzipped file into the repo.

The example works without the compressed stylesheet showing the extra `Cache-Control` header, `Content-Encoding` is kind of optional.

I always avoid adding generated content (compiles, binaries, caches, compressed files, etc.) to a repository – these bloat up reposiries quickly if changed (ever tried to clone the Arduino repo?).
That's what [releases](https://help.github.com/articles/about-releases/) or Git LFS can solve.

But we're talking about 57 bytes here. So it's not about repo size ;)  
If you prefer having the "complete" example in the repo, I can add it of course.

**Comment by pfalcon** [comment]
@orzechow : Thanks for getting back to this!

> I always avoid adding generated content

Yeah, I definitely try to avoid that too, but here we're indeed talking about adding handful of binary bytes and having a complete example working out of the box, vs not having that. I didn't intend to add more and more examples originally, but as the decision to go that way was taken, it makes sense to make it as easy as possible for people to try those examples ;-).

**Comment by orzechow** [comment]
Well then, added `style.css.gz` and squashed the commit again.

**Comment by pfalcon** [comment]
Great! I've modified the example to os.listdir() - with both *.css and *.css.gz present, we just send one of them. Also, added example of specifying headers as a dict (on "/"), now this example should document all the features in that regard. Final result is 38081e95e2b9f997669e0108fb0672df2f93a1fc.

Thanks for contributing!

**Comment by orzechow** [comment]
Thanks, looks great!

PS: I noticed that you pass the content type as string, while the extra headers are still byte arrays. Would you mind to explain, when one or the other should be used?

**Comment by pfalcon** [comment]
> I noticed that you pass the content type as string, while the extra headers are still byte arrays. Would you mind to explain, when one or the other should be used?

So, first of all, MicroPython, comparing to CPython, has relaxed `bytes` vs `str` handing: where CPython does (or would) mandate `bytes`, `str` can also be passed. Beyond that, it's just common sense that normal "string like" params would be `str`, unless specified otherwise. So, content type alone was always considered a string. But "raw" headers, as we discussed, are bytes, while when it dict "can" be strings too.

That all may need to be tightened up if/when I revive "CPython port" (though maybe it will be exactly a port, i.e. a separate codebase).

All in all, there's no hard science (at least so far), and I would accept criticism/pointers to inconsistencies in a separate ticket (but fixing that would be low enough priority for now).

**Comment by orzechow** [comment]
Thanks for the explanation!

So in MicroPython it doesn't make a difference in performance? That's what I was wandering about.  
It wasn't really clear to me, because the [MicroPython documentation](https://docs.micropython.org/en/latest/pyboard/reference/constrained.html#execution-phase) mentions that bytearrays ensure to use only one byte per character, while strings might use two (for Unicode characters).

I agree that "raw" headers can be seen as bytes, while the normal params are treated as strings. One inconsistency though (and the reason I wondered) is that both are passed to `uasyncio.StreamWriter.awrite()`

**Comment by pfalcon** [comment]
> So in MicroPython it doesn't make a difference in performance?

Depending on what performance you mean. I'd put it differently: to not add performance and memory allocation overhead, MicroPython allows to pass `str` to many functions which are defined to accept `bytes`.

> One inconsistency though (and the reason I wondered) is that both are passed to

Again, good way to look at that is not "inconsistency", but "freedom". It may be hacky freedom, for example, it works only for ASCII strings. My recommendation is to not rely on it and do it properly, in CPython-defined way (i.e. pass `bytes`, as awrite() is indeed defined to accept that). However, when it comes to using it myself, I find it very practical to pass (literal) strings directly, and (ab)use that possibility all the time. Don't follow me :-D.

**Comment by orzechow** [comment]
All right, got it :D

However if you recommend doing it properly and passing bytes, the examples should reflect that (because that's what people take as a starting point) ;)

**Comment by pfalcon** [comment]
Right, one sweet day ;-).

My real underlying concern is suitability of Python3 for "beginners" and "not hardcore programmers". When you write `func("str")`, everyone with basic programming skills would understand what `"str"` is. It's quite different for `func(b"str")`. People coming from different languages won't know what that `b` means, nor it's exactly easy to explain to a novice who doesn't know concept of weakly vs strongly typed languages. I accepted the need of `"str"` vs `b"str"` in Python3 long ago. I'm not sure that everyone in the world did.

So yeah, it will need to be fixed eventually, but I put off that day until later and later...

**Pull request closed without merging**
